import numpy as np
import matplotlib.pyplot as plt
import bisect
import time
import sys
sys.path.append('../')
from controllers import *
from scipy.interpolate import interp1d


def generate_SNN_training_set(recording, frame_rate):
    data = np.loadtxt("./data/" + recording)

    recording_time = 1 # Recording duration in seconds
    buffer_size = 10
    frame_numbers = np.arange(buffer_size, buffer_size + int(recording_time*frame_rate)) - buffer_size
    # frame_numbers = data[buffer_size:buffer_size + int(recording_time*frame_rate), 0] - buffer_size
    print(frame_numbers)
    frame_times = np.floor(1000*(1/frame_rate)*np.array(frame_numbers))
    print(frame_times)
    data = data[buffer_size:buffer_size + int(recording_time*frame_rate), :]
    # print(data.shape)

    T = frame_times[-1]  # recording time in milliseconds
    #
    time_steps = np.arange(0, T+1)
    # print(time_steps)

    angles_rescaled = np.zeros((data.shape[1], len(time_steps)))
    # print(angles_rescaled.shape)

    for joint in range(data.shape[1]):
        f1 = interp1d(frame_times, data[:, joint], kind='linear', fill_value='extrapolate')
        # angles_rescaled[joint, :] = (180/np.pi)*f1(time_steps)
        angles_rescaled[joint, :] = f1(time_steps)

    np.savetxt('./data/SNN_train_data.txt', angles_rescaled)

    return frame_times


def plot_optimal_controller(handle, xlabel, ylabel, title, actual, target, controlled):
    """
    Plotting function to record the control of each joint

    :param handle: Figure handle
    :param xlabel: Label of x-axis
    :param ylabel: Label of y-axis
    :param title: Figure title
    :param actual: Actual joint angles
    :param target: Discretized target points for the joint angle
    :param controlled: Joint angle generated by the controller
    :return: Figure handle
    """
    if not handle:
        fig, axs = plt.subplots(1, 1, figsize=(8, 8), dpi=80)
    else:
        fig, axs = handle

    target = target.flatten()
    controlled = controlled.flatten()

    fig.suptitle(title)
    axs.plot(actual)
    # axs.plot(target)
    axs.plot(controlled)
    axs.set(xlabel=xlabel, ylabel=ylabel)

    fig.tight_layout()

    return [fig, axs]


def save_fig(handle, save_path, file_name):
    """
    Helper function for saving a figure

    :param handle: figure handle
    :param save_path: path where the figure will be saved
    :param file_name: name of the figure file
    """
    fig, axs = handle
    fig.savefig(save_path + '/' + file_name + ".svg")
    plt.close(fig)


def argsort(seq):
    """
    Equivalent of the numpy function for regular python lists

    :param seq: list to identify the order that sorts its arguments
    :return: list of indices that sort the list
    """
    return sorted(range(len(seq)), key=seq.__getitem__)


def estimDeriv(x, sim_ts, der_window):
    """
    Estimate derivative of the variables in an array

    :param x: 2D array whose rows are variables whose derivative will be estimated (np.array)
    :param sim_ts: Simulation timestep
    :param der_window: Window length for derivative estimation
    :return: der: Derivative estimate
    """
    der = np.zeros((x.shape[0], x.shape[1]))
    cur_ts = 1
    while cur_ts < x.shape[1]:
        if cur_ts * sim_ts < der_window:
            der[:, cur_ts] = (x[:, cur_ts] - x[:, 0]) / (cur_ts * sim_ts)
        else:
            der[:, cur_ts] = (x[:, cur_ts] - x[:, int((cur_ts - der_window / sim_ts))]) / (der_window * sim_ts)
        cur_ts += 1
    return der[:, 1:]


def zero_crossing(x):
    """
    Find the zero-crossings of the variables in an array

    :param x: 2D array whose rows are variables whose zero-crossings will be detected (np.array)
    :return: zero_crossings: 2D array with binary values as a mask denoting the zero-crossings of the variables
    """
    zero_crossings = np.zeros((x.shape[0], x.shape[1]))
    cur_ts = 3
    while cur_ts < x.shape[1]:
        zero_crossings[:, cur_ts] = 1 * np.sign(x[:, cur_ts] * x[:, cur_ts - 3]) == -1
        cur_ts += 1
    return zero_crossings


def automatic_state_sampling(avg_angles, moving_joint_threshold, deriv_window, oversampling):
    """
    Sampling the average angles and provide target angles for the controller to replicate the movements.
    The sampling method consists of the following steps:
    1) Estimate the derivatives of the angles
    2) Skip the joints whose angle changes less than moving_joint_threshold = 5 degrees
    3) Detect the zero crossings of the derivatives
    4) Drop zero crossings that are closer than time_dist = 50 in time
    5) Use the remaining zero crossings as triggers in time
    6) Find the min/max values between consecutive triggers
    7) Specify target angles as the min/max value that is further from the value at the previous trigger time

    :param avg_angles: 2D array whose rows are the angles of the 22 joints over time (np.array)
    :param moving_joint_threshold: threshold over which a joint is considered to be moving (filter out idle joints)
    :param deriv_window: length of window over which the derivative is estimated
    :param oversampling: How many times the points between triggers will be oversampled
    :return: trigger: trigger times for the target setting (list of 22 lists, where each has the triggers of the joint)
             target_angles: 2D array with the target angles for each joint over time
    """
    joints, timesteps = avg_angles.shape
    target_angles = np.multiply(np.ones_like(avg_angles), avg_angles[:, -1][:, np.newaxis])

    # moving_joint_threshold = 0.25
    angles_der = estimDeriv(avg_angles, 1, deriv_window)
    zero_crossings_mask = zero_crossing(angles_der)
    triggers = []
    time_dist = 20
    joint = 0
    tr = [0, timesteps - 1]
    if max(avg_angles[joint, :] - min(avg_angles[joint, :])) > moving_joint_threshold:  # Skip non-moving joints
        zc = np.where(zero_crossings_mask[joint, :] == 1)[0]
        tr = np.insert(tr, 1, zc)
    triggers.append(np.array(tr))
    jj = 1
    while jj < len(triggers[joint]):  # Drop triggers that are close in time
        if triggers[joint][jj] - triggers[joint][jj - 1] < time_dist:
            triggers[joint] = np.delete(triggers[joint], jj)
            jj -= 1
        jj += 1

    # Add intermediate samples
    for _ in range(oversampling):
        oversampled_triggers = ((triggers[joint][1:] + triggers[joint][:-1]) / 2).astype(int)
        triggers[joint] = np.unique(np.concatenate((triggers[joint], oversampled_triggers)))
    
    # Oversample joint 2 of CMU dataset to capture translation
    if joint == 2 and oversampling < 5:
        for _ in range(10):
            oversampled_triggers = ((triggers[joint][1:] + triggers[joint][:-1]) / 2).astype(int)
            triggers[joint] = np.unique(np.concatenate((triggers[joint], oversampled_triggers)))
            
    for kk in range(len(triggers[joint]) - 1):
        cur = avg_angles[joint, triggers[joint][kk]]
        range_min = min(avg_angles[joint, triggers[joint][kk]:triggers[joint][kk + 1]])
        range_max = max(avg_angles[joint, triggers[joint][kk]:triggers[joint][kk + 1]])
        if np.abs(cur - range_min) > np.abs(range_max - cur):
            target_angles[joint, triggers[joint][kk]:triggers[joint][kk + 1]] = range_min
            # target_angles[joint, triggers[joint][kk]:triggers[joint][kk + 1]] = avg_angles[joint, triggers[joint][kk + 1]]
        else:
            target_angles[joint, triggers[joint][kk]:triggers[joint][kk + 1]] = range_max
            # target_angles[joint, triggers[joint][kk]:triggers[joint][kk + 1]] = avg_angles[joint, triggers[joint][kk + 1]]

    # print("Number of parameters is: ", len(triggers[joint]))
    return triggers, target_angles


def RMSE(x, y):
    """
    Calculate the RMSE between actual(x) and predicted(y) values normalized over the range of the actual values.
    x and y are vectors (curve values over time) and the function returns a single value.

    :param x: Values over time for the first curve (actual values)
    :param y: Values over time for the second curve (predicted values)
    :return: Scalar or vector with the RMSE
    """
    act_rng = np.abs(np.max(x) - np.min(x))
    e_sq = (x - y) ** 2
    return np.sqrt(np.mean(e_sq)) / act_rng


def add_offsprings(father, heap):
    """
    Identifying and generating the possible children of each controller
    :param father: Parent controller node
    :param heap: Heap where offsprings will be added
    :return: heap : Updated heap with new offsprings added
    """
    strengths = [3, 5, 7, 10, 12, 15, 20, 35, 50]
    changes = [i for i, e in enumerate(father) if e == 0]
    for change in changes:
        child = father.copy()
        child[change] += 1
        # print(child)
        heap.append(child)
    for strength in strengths:
        child = father.copy()
        if child[5] != strength:
            child[5] = strength
            heap.append(child)
    return heap


def perform_gesture(ground_truth, goals, ctrl_modules):
    """
    Evaluation function running the controller on the given test set

    :param ground_truth: Vector with the actual values of the control variable that need to be approximated (np.array)
    :param goals: Discretized target values used for the approximation of the control variable (np.array)
    :param ctrl_modules: Specifications of the used controller - Vector with 0/1 for different specs and the size of the MN pool (list)
    :return: control_angles : predicted joint angles by the current controller (np.array)
    """
    dt = 0.1  # integration step (ms)
    T = goals.shape[1]
    time = np.arange(0, T - dt, dt)

    control_angles = np.zeros_like(goals)
    hand_controller = AgentController(dt, ground_truth[:, 0], Speed_control=ctrl_modules[0],
                                      Facilitation=ctrl_modules[1:3], PSI=ctrl_modules[3:5],
                                      MN_pool_size=ctrl_modules[5])

    for t in time:
        hand_controller.update_state(goals[:, int(np.floor(t))])
        if round(t, 2) == round(t):
            control_angles[:, round(t)] = hand_controller.get_state()
    return control_angles


def search_ctrlrs_smart(joint_angle, target_angles):
    """
    Smart search for the best controller using A*-like evolutionary algorithm

    :param joint_angle: Actual values of the control variable over time (np.array)
    :param target_angles: Discretized target values used for the approximation of the control variable (np.array)
    :return: ctrl_angles : Predicted joint angles by the current controller (np.array)
    """
    t = time.time()
    ctrlr_counter = 0
    offspring_heap = [[0, 0, 0, 0, 0, 1]]
    gave_birth = []
    offspring_ID = [[0, 0, 0, 0, 0, 1]]

    module_status = offspring_ID[0]
    ctrl_angles = perform_gesture(joint_angle.reshape(1, joint_angle.shape[0]), target_angles.reshape(1, target_angles.shape[1]), module_status)
    offspring_cost = [RMSE(joint_angle, ctrl_angles)]
    # while offspring_cost[0] > 0.1 and ctrlr_counter < len(ctrlr_specs)-1:
    while offspring_cost[0] > 0.08 and ctrlr_counter < 270:
        # print("Searching for controller...")
        for i, offspring in enumerate(offspring_ID):
            if offspring_ID[i] not in gave_birth:
                gave_birth.append(offspring_ID[i])
                break

        offspring_heap = add_offsprings(offspring_ID[i], offspring_heap)
        while len(offspring_heap) > 0:
            # print(len(offspring_heap))
            offspring = offspring_heap.pop(0)
            if offspring not in offspring_ID:
                ctrlr_counter += 1
                ctrl_angles = perform_gesture(joint_angle.reshape(1, joint_angle.shape[0]),
                                              target_angles.reshape(1, target_angles.shape[1]), offspring)
                cost = RMSE(joint_angle, ctrl_angles)
                ind = bisect.bisect_left(offspring_cost, cost)
                offspring_cost.insert(ind, cost)
                offspring_ID.insert(ind, offspring)
                # offspring_cost.append(RMSE(joint_angle, ctrl_angles))
                # offspring_ID.append(offspring)

        # ind = argsort(offspring_cost)
        # offspring_cost = [offspring_cost[i] for i in ind]
        # offspring_ID = [offspring_ID[i] for i in ind]
    print("Best controller is: " + str(offspring_ID[0]) + " with RMSE " + str(offspring_cost[0]) + " after " + str(ctrlr_counter) + " tests")
    print("Joint search time is: ", time.time() - t)
    ctrl_angles = perform_gesture(joint_angle.reshape(1, joint_angle.shape[0]),
                                  target_angles.reshape(1, target_angles.shape[1]), offspring_ID[0])

    return ctrl_angles, offspring_ID[0]


def read_controller_specs(file_dir):
    ctrlr_strings = open(file_dir, 'r').read().splitlines()
    ctrlr_specs = []
    for str in ctrlr_strings:
        ctrlr_specs.append([int(item) for item in str.split(',') if item.isdigit()])
    ctrlr_specs = np.array(ctrlr_specs)

    return ctrlr_specs